### ISSUE TITLE
Night mode not working properly

### ISSUE THREAD

**Issue by FuzzyMistborn** [openipcamera/openipc-firmware#36]
At night, there's essentially no IR, all i see is black.  I've tried toggling the auto night mode/IR sensors on and off to no effect.  Also, the 4 IR lights are on all the time, not sure that's related or not.

**Comment by openipcamera** [comment]
There is a fix in an updated run.sh coming soon.

**Comment by arunned** [comment]
is the night vision fixed in v26?

**Comment by FuzzyMistborn** [comment]
Kinda.  There was a patch that didn't make the 0.2.6 release but will be merged.  Auto night vision is not working but that's because the v2's handle things differently than the v1s did.

**Comment by derspion318** [comment]
The patch you speak of that didn't make 0.2.6, is that the fix for the v2 auto night vision?

**Comment by FuzzyMistborn** [comment]
No, there's no fix at this time for auto night vision, just a fix for night vision (so it's not all black)

**Comment by bachya** [comment]
I just updated to 0.2.6 and am still seeing black. I've tried every combination of turning on/off the IR LED, IR Cut, Auto Night Mode, etc.

**Comment by FuzzyMistborn** [comment]
@bachya the patch didn't make 0.2.6 apparently and will be in the next release.  See #48 and you can implement the changes yourself.
